ssh bsidna4 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_0 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_0 /mnt/work/blast_filter_out/tmp/S2_m.fasta_0 &
ssh bsidna5 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_1 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_1 /mnt/work/blast_filter_out/tmp/S2_m.fasta_1 &
ssh bsidna6 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_2 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_2 /mnt/work/blast_filter_out/tmp/S2_m.fasta_2 &
ssh bsidna7 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_3 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_3 /mnt/work/blast_filter_out/tmp/S2_m.fasta_3 &
ssh bsidna8 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_4 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_4 /mnt/work/blast_filter_out/tmp/S2_m.fasta_4 &
ssh bsidna9 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_5 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_5 /mnt/work/blast_filter_out/tmp/S2_m.fasta_5 &
ssh bsidna10 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_6 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_6 /mnt/work/blast_filter_out/tmp/S2_m.fasta_6 &
ssh bsidna11 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_7 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_7 /mnt/work/blast_filter_out/tmp/S2_m.fasta_7 &
ssh bsidna14 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_8 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_8 /mnt/work/blast_filter_out/tmp/S2_m.fasta_8 &
ssh bsidna15 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_9 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_9 /mnt/work/blast_filter_out/tmp/S2_m.fasta_9 &
ssh bsidna19 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_10 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_10 /mnt/work/blast_filter_out/tmp/S2_m.fasta_10 &
ssh bsidna20 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_11 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_11 /mnt/work/blast_filter_out/tmp/S2_m.fasta_11 &
ssh bsidna23 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_12 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_12 /mnt/work/blast_filter_out/tmp/S2_m.fasta_12 &
ssh bsidna24 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_13 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_13 /mnt/work/blast_filter_out/tmp/S2_m.fasta_13 &
ssh bsidna25 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_14 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_14 /mnt/work/blast_filter_out/tmp/S2_m.fasta_14 &
ssh bsidna26 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_15 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_15 /mnt/work/blast_filter_out/tmp/S2_m.fasta_15 &
ssh bsidna27 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_16 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_16 /mnt/work/blast_filter_out/tmp/S2_m.fasta_16 &
ssh bsidna28 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_17 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_17 /mnt/work/blast_filter_out/tmp/S2_m.fasta_17 &
ssh bsidna29 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_18 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_18 /mnt/work/blast_filter_out/tmp/S2_m.fasta_18 &
ssh bsidna30 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_19 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_19 /mnt/work/blast_filter_out/tmp/S2_m.fasta_19 &
wait
ssh bsidna4 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_20 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_20 /mnt/work/blast_filter_out/tmp/S2_m.fasta_20 &
ssh bsidna5 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_21 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_21 /mnt/work/blast_filter_out/tmp/S2_m.fasta_21 &
ssh bsidna6 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_22 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_22 /mnt/work/blast_filter_out/tmp/S2_m.fasta_22 &
ssh bsidna7 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_23 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_23 /mnt/work/blast_filter_out/tmp/S2_m.fasta_23 &
ssh bsidna8 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_24 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_24 /mnt/work/blast_filter_out/tmp/S2_m.fasta_24 &
ssh bsidna9 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_25 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_25 /mnt/work/blast_filter_out/tmp/S2_m.fasta_25 &
ssh bsidna10 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_26 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_26 /mnt/work/blast_filter_out/tmp/S2_m.fasta_26 &
ssh bsidna11 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_27 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_27 /mnt/work/blast_filter_out/tmp/S2_m.fasta_27 &
ssh bsidna14 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_28 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_28 /mnt/work/blast_filter_out/tmp/S2_m.fasta_28 &
ssh bsidna15 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_29 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_29 /mnt/work/blast_filter_out/tmp/S2_m.fasta_29 &
ssh bsidna19 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_30 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_30 /mnt/work/blast_filter_out/tmp/S2_m.fasta_30 &
ssh bsidna20 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_31 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_31 /mnt/work/blast_filter_out/tmp/S2_m.fasta_31 &
ssh bsidna23 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_32 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_32 /mnt/work/blast_filter_out/tmp/S2_m.fasta_32 &
ssh bsidna24 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_33 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_33 /mnt/work/blast_filter_out/tmp/S2_m.fasta_33 &
ssh bsidna25 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_34 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_34 /mnt/work/blast_filter_out/tmp/S2_m.fasta_34 &
ssh bsidna26 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_35 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_35 /mnt/work/blast_filter_out/tmp/S2_m.fasta_35 &
ssh bsidna27 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_36 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_36 /mnt/work/blast_filter_out/tmp/S2_m.fasta_36 &
ssh bsidna28 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_37 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_37 /mnt/work/blast_filter_out/tmp/S2_m.fasta_37 &
ssh bsidna29 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_38 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_38 /mnt/work/blast_filter_out/tmp/S2_m.fasta_38 &
ssh bsidna30 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_39 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_39 /mnt/work/blast_filter_out/tmp/S2_m.fasta_39 &
wait
ssh bsidna4 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_40 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_40 /mnt/work/blast_filter_out/tmp/S2_m.fasta_40 &
ssh bsidna5 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_41 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_41 /mnt/work/blast_filter_out/tmp/S2_m.fasta_41 &
ssh bsidna6 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_42 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_42 /mnt/work/blast_filter_out/tmp/S2_m.fasta_42 &
ssh bsidna7 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_43 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_43 /mnt/work/blast_filter_out/tmp/S2_m.fasta_43 &
ssh bsidna8 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_44 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_44 /mnt/work/blast_filter_out/tmp/S2_m.fasta_44 &
ssh bsidna9 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_45 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_45 /mnt/work/blast_filter_out/tmp/S2_m.fasta_45 &
ssh bsidna10 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_46 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_46 /mnt/work/blast_filter_out/tmp/S2_m.fasta_46 &
ssh bsidna11 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_47 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_47 /mnt/work/blast_filter_out/tmp/S2_m.fasta_47 &
ssh bsidna14 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_48 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_48 /mnt/work/blast_filter_out/tmp/S2_m.fasta_48 &
ssh bsidna15 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S2_m.xml_49 /mnt/work/blast_filter_out/tmp/S2_prem.fasta_49 /mnt/work/blast_filter_out/tmp/S2_m.fasta_49 &
ssh bsidna19 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_0 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_0 /mnt/work/blast_filter_out/tmp/S1_m.fasta_0 &
ssh bsidna20 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_1 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_1 /mnt/work/blast_filter_out/tmp/S1_m.fasta_1 &
ssh bsidna23 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_2 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_2 /mnt/work/blast_filter_out/tmp/S1_m.fasta_2 &
ssh bsidna24 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_3 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_3 /mnt/work/blast_filter_out/tmp/S1_m.fasta_3 &
ssh bsidna25 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_4 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_4 /mnt/work/blast_filter_out/tmp/S1_m.fasta_4 &
ssh bsidna26 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_5 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_5 /mnt/work/blast_filter_out/tmp/S1_m.fasta_5 &
ssh bsidna27 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_6 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_6 /mnt/work/blast_filter_out/tmp/S1_m.fasta_6 &
ssh bsidna28 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_7 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_7 /mnt/work/blast_filter_out/tmp/S1_m.fasta_7 &
ssh bsidna29 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_8 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_8 /mnt/work/blast_filter_out/tmp/S1_m.fasta_8 &
ssh bsidna30 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_9 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_9 /mnt/work/blast_filter_out/tmp/S1_m.fasta_9 &
wait
ssh bsidna4 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_10 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_10 /mnt/work/blast_filter_out/tmp/S1_m.fasta_10 &
ssh bsidna5 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_11 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_11 /mnt/work/blast_filter_out/tmp/S1_m.fasta_11 &
ssh bsidna6 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_12 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_12 /mnt/work/blast_filter_out/tmp/S1_m.fasta_12 &
ssh bsidna7 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_13 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_13 /mnt/work/blast_filter_out/tmp/S1_m.fasta_13 &
ssh bsidna8 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_14 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_14 /mnt/work/blast_filter_out/tmp/S1_m.fasta_14 &
ssh bsidna9 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_15 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_15 /mnt/work/blast_filter_out/tmp/S1_m.fasta_15 &
ssh bsidna10 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_16 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_16 /mnt/work/blast_filter_out/tmp/S1_m.fasta_16 &
ssh bsidna11 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_17 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_17 /mnt/work/blast_filter_out/tmp/S1_m.fasta_17 &
ssh bsidna14 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_18 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_18 /mnt/work/blast_filter_out/tmp/S1_m.fasta_18 &
ssh bsidna15 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_19 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_19 /mnt/work/blast_filter_out/tmp/S1_m.fasta_19 &
ssh bsidna19 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_20 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_20 /mnt/work/blast_filter_out/tmp/S1_m.fasta_20 &
ssh bsidna20 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_21 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_21 /mnt/work/blast_filter_out/tmp/S1_m.fasta_21 &
ssh bsidna23 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_22 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_22 /mnt/work/blast_filter_out/tmp/S1_m.fasta_22 &
ssh bsidna24 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_23 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_23 /mnt/work/blast_filter_out/tmp/S1_m.fasta_23 &
ssh bsidna25 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_24 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_24 /mnt/work/blast_filter_out/tmp/S1_m.fasta_24 &
ssh bsidna26 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_25 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_25 /mnt/work/blast_filter_out/tmp/S1_m.fasta_25 &
ssh bsidna27 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_26 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_26 /mnt/work/blast_filter_out/tmp/S1_m.fasta_26 &
ssh bsidna28 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_27 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_27 /mnt/work/blast_filter_out/tmp/S1_m.fasta_27 &
ssh bsidna29 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_28 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_28 /mnt/work/blast_filter_out/tmp/S1_m.fasta_28 &
ssh bsidna30 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_29 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_29 /mnt/work/blast_filter_out/tmp/S1_m.fasta_29 &
wait
ssh bsidna4 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_30 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_30 /mnt/work/blast_filter_out/tmp/S1_m.fasta_30 &
ssh bsidna5 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_31 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_31 /mnt/work/blast_filter_out/tmp/S1_m.fasta_31 &
ssh bsidna6 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_32 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_32 /mnt/work/blast_filter_out/tmp/S1_m.fasta_32 &
ssh bsidna7 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_33 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_33 /mnt/work/blast_filter_out/tmp/S1_m.fasta_33 &
ssh bsidna8 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_34 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_34 /mnt/work/blast_filter_out/tmp/S1_m.fasta_34 &
ssh bsidna9 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_35 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_35 /mnt/work/blast_filter_out/tmp/S1_m.fasta_35 &
ssh bsidna10 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_36 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_36 /mnt/work/blast_filter_out/tmp/S1_m.fasta_36 &
ssh bsidna11 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_37 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_37 /mnt/work/blast_filter_out/tmp/S1_m.fasta_37 &
ssh bsidna14 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_38 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_38 /mnt/work/blast_filter_out/tmp/S1_m.fasta_38 &
ssh bsidna15 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_39 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_39 /mnt/work/blast_filter_out/tmp/S1_m.fasta_39 &
ssh bsidna19 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_40 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_40 /mnt/work/blast_filter_out/tmp/S1_m.fasta_40 &
ssh bsidna20 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_41 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_41 /mnt/work/blast_filter_out/tmp/S1_m.fasta_41 &
ssh bsidna23 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_42 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_42 /mnt/work/blast_filter_out/tmp/S1_m.fasta_42 &
ssh bsidna24 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_43 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_43 /mnt/work/blast_filter_out/tmp/S1_m.fasta_43 &
ssh bsidna25 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_44 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_44 /mnt/work/blast_filter_out/tmp/S1_m.fasta_44 &
ssh bsidna26 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_45 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_45 /mnt/work/blast_filter_out/tmp/S1_m.fasta_45 &
ssh bsidna27 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_46 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_46 /mnt/work/blast_filter_out/tmp/S1_m.fasta_46 &
ssh bsidna28 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_47 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_47 /mnt/work/blast_filter_out/tmp/S1_m.fasta_47 &
ssh bsidna29 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_48 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_48 /mnt/work/blast_filter_out/tmp/S1_m.fasta_48 &
ssh bsidna30 /mnt/cluster/xdeng/script/blast_filter_NR_mys.py /mnt/work/blast_filter_out/tmp/S1_m.xml_49 /mnt/work/blast_filter_out/tmp/S1_prem.fasta_49 /mnt/work/blast_filter_out/tmp/S1_m.fasta_49 &
wait
