ssh bsidna5 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_1 -f /mnt/work/fastq/S1.fa -S /mnt/work/NT/S1_1.sam &
ssh bsidna6 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_2 -f /mnt/work/fastq/S1.fa -S /mnt/work/NT/S1_2.sam &
ssh bsidna7 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_3 -f /mnt/work/fastq/S1.fa -S /mnt/work/NT/S1_3.sam &
ssh bsidna8 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_4 -f /mnt/work/fastq/S1.fa -S /mnt/work/NT/S1_4.sam &
ssh bsidna9 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_5 -f /mnt/work/fastq/S1.fa -S /mnt/work/NT/S1_5.sam &
ssh bsidna10 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_6 -f /mnt/work/fastq/S1.fa -S /mnt/work/NT/S1_6.sam &
ssh bsidna11 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_7 -f /mnt/work/fastq/S1.fa -S /mnt/work/NT/S1_7.sam &
ssh bsidna14 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_8 -f /mnt/work/fastq/S1.fa -S /mnt/work/NT/S1_8.sam &
ssh bsidna15 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_9 -f /mnt/work/fastq/S1.fa -S /mnt/work/NT/S1_9.sam &
ssh bsidna19 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_10 -f /mnt/work/fastq/S1.fa -S /mnt/work/NT/S1_10.sam &
ssh bsidna20 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_11 -f /mnt/work/fastq/S1.fa -S /mnt/work/NT/S1_11.sam &
ssh bsidna23 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_12 -f /mnt/work/fastq/S1.fa -S /mnt/work/NT/S1_12.sam &
ssh bsidna24 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_13 -f /mnt/work/fastq/S1.fa -S /mnt/work/NT/S1_13.sam &
ssh bsidna25 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_14 -f /mnt/work/fastq/S1.fa -S /mnt/work/NT/S1_14.sam &
ssh bsidna26 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_1 -f /mnt/work/fastq/S2.fa -S /mnt/work/NT/S2_1.sam &
ssh bsidna27 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_2 -f /mnt/work/fastq/S2.fa -S /mnt/work/NT/S2_2.sam &
ssh bsidna28 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_3 -f /mnt/work/fastq/S2.fa -S /mnt/work/NT/S2_3.sam &
ssh bsidna29 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_4 -f /mnt/work/fastq/S2.fa -S /mnt/work/NT/S2_4.sam &
ssh bsidna30 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_5 -f /mnt/work/fastq/S2.fa -S /mnt/work/NT/S2_5.sam &
ssh bsidna4 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_6 -f /mnt/work/fastq/S2.fa -S /mnt/work/NT/S2_6.sam &
wait
ssh bsidna5 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_7 -f /mnt/work/fastq/S2.fa -S /mnt/work/NT/S2_7.sam &
ssh bsidna6 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_8 -f /mnt/work/fastq/S2.fa -S /mnt/work/NT/S2_8.sam &
ssh bsidna7 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_9 -f /mnt/work/fastq/S2.fa -S /mnt/work/NT/S2_9.sam &
ssh bsidna8 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_10 -f /mnt/work/fastq/S2.fa -S /mnt/work/NT/S2_10.sam &
ssh bsidna9 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_11 -f /mnt/work/fastq/S2.fa -S /mnt/work/NT/S2_11.sam &
ssh bsidna10 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_12 -f /mnt/work/fastq/S2.fa -S /mnt/work/NT/S2_12.sam &
ssh bsidna11 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_13 -f /mnt/work/fastq/S2.fa -S /mnt/work/NT/S2_13.sam &
ssh bsidna14 /mnt/cluster/xdeng/tools/bowtie2-2.2.4/bowtie2 --quiet --local --very-fast-local --no-hd --reorder -p 8 -x /mnt/cluster/xdeng/taxon/nt_14 -f /mnt/work/fastq/S2.fa -S /mnt/work/NT/S2_14.sam &
