ssh bsidna4 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_0 /mnt/work/blast_filter_out/tmp/S1_m.fasta_0_p &
ssh bsidna5 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_1 /mnt/work/blast_filter_out/tmp/S1_m.fasta_1_p &
ssh bsidna6 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_2 /mnt/work/blast_filter_out/tmp/S1_m.fasta_2_p &
ssh bsidna7 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_3 /mnt/work/blast_filter_out/tmp/S1_m.fasta_3_p &
ssh bsidna8 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_4 /mnt/work/blast_filter_out/tmp/S1_m.fasta_4_p &
ssh bsidna9 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_5 /mnt/work/blast_filter_out/tmp/S1_m.fasta_5_p &
ssh bsidna10 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_6 /mnt/work/blast_filter_out/tmp/S1_m.fasta_6_p &
ssh bsidna11 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_7 /mnt/work/blast_filter_out/tmp/S1_m.fasta_7_p &
ssh bsidna14 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_8 /mnt/work/blast_filter_out/tmp/S1_m.fasta_8_p &
ssh bsidna15 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_9 /mnt/work/blast_filter_out/tmp/S1_m.fasta_9_p &
ssh bsidna19 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_10 /mnt/work/blast_filter_out/tmp/S1_m.fasta_10_p &
ssh bsidna20 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_11 /mnt/work/blast_filter_out/tmp/S1_m.fasta_11_p &
ssh bsidna23 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_12 /mnt/work/blast_filter_out/tmp/S1_m.fasta_12_p &
ssh bsidna24 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_13 /mnt/work/blast_filter_out/tmp/S1_m.fasta_13_p &
ssh bsidna25 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_14 /mnt/work/blast_filter_out/tmp/S1_m.fasta_14_p &
ssh bsidna26 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_15 /mnt/work/blast_filter_out/tmp/S1_m.fasta_15_p &
ssh bsidna27 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_16 /mnt/work/blast_filter_out/tmp/S1_m.fasta_16_p &
ssh bsidna28 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_17 /mnt/work/blast_filter_out/tmp/S1_m.fasta_17_p &
ssh bsidna29 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_18 /mnt/work/blast_filter_out/tmp/S1_m.fasta_18_p &
ssh bsidna30 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_19 /mnt/work/blast_filter_out/tmp/S1_m.fasta_19_p &
wait
ssh bsidna4 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_20 /mnt/work/blast_filter_out/tmp/S1_m.fasta_20_p &
ssh bsidna5 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_21 /mnt/work/blast_filter_out/tmp/S1_m.fasta_21_p &
ssh bsidna6 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_22 /mnt/work/blast_filter_out/tmp/S1_m.fasta_22_p &
ssh bsidna7 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_23 /mnt/work/blast_filter_out/tmp/S1_m.fasta_23_p &
ssh bsidna8 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_24 /mnt/work/blast_filter_out/tmp/S1_m.fasta_24_p &
ssh bsidna9 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_25 /mnt/work/blast_filter_out/tmp/S1_m.fasta_25_p &
ssh bsidna10 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_26 /mnt/work/blast_filter_out/tmp/S1_m.fasta_26_p &
ssh bsidna11 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_27 /mnt/work/blast_filter_out/tmp/S1_m.fasta_27_p &
ssh bsidna14 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_28 /mnt/work/blast_filter_out/tmp/S1_m.fasta_28_p &
ssh bsidna15 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_29 /mnt/work/blast_filter_out/tmp/S1_m.fasta_29_p &
ssh bsidna19 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_30 /mnt/work/blast_filter_out/tmp/S1_m.fasta_30_p &
ssh bsidna20 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_31 /mnt/work/blast_filter_out/tmp/S1_m.fasta_31_p &
ssh bsidna23 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_32 /mnt/work/blast_filter_out/tmp/S1_m.fasta_32_p &
ssh bsidna24 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_33 /mnt/work/blast_filter_out/tmp/S1_m.fasta_33_p &
ssh bsidna25 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_34 /mnt/work/blast_filter_out/tmp/S1_m.fasta_34_p &
ssh bsidna26 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_35 /mnt/work/blast_filter_out/tmp/S1_m.fasta_35_p &
ssh bsidna27 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_36 /mnt/work/blast_filter_out/tmp/S1_m.fasta_36_p &
ssh bsidna28 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_37 /mnt/work/blast_filter_out/tmp/S1_m.fasta_37_p &
ssh bsidna29 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_38 /mnt/work/blast_filter_out/tmp/S1_m.fasta_38_p &
ssh bsidna30 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_39 /mnt/work/blast_filter_out/tmp/S1_m.fasta_39_p &
wait
ssh bsidna4 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_40 /mnt/work/blast_filter_out/tmp/S1_m.fasta_40_p &
ssh bsidna5 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_41 /mnt/work/blast_filter_out/tmp/S1_m.fasta_41_p &
ssh bsidna6 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_42 /mnt/work/blast_filter_out/tmp/S1_m.fasta_42_p &
ssh bsidna7 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_43 /mnt/work/blast_filter_out/tmp/S1_m.fasta_43_p &
ssh bsidna8 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_44 /mnt/work/blast_filter_out/tmp/S1_m.fasta_44_p &
ssh bsidna9 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_45 /mnt/work/blast_filter_out/tmp/S1_m.fasta_45_p &
ssh bsidna10 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_46 /mnt/work/blast_filter_out/tmp/S1_m.fasta_46_p &
ssh bsidna11 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_47 /mnt/work/blast_filter_out/tmp/S1_m.fasta_47_p &
ssh bsidna14 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_48 /mnt/work/blast_filter_out/tmp/S1_m.fasta_48_p &
ssh bsidna15 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S1_m.fasta_49 /mnt/work/blast_filter_out/tmp/S1_m.fasta_49_p &
ssh bsidna19 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_0 /mnt/work/blast_filter_out/tmp/S2_m.fasta_0_p &
ssh bsidna20 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_1 /mnt/work/blast_filter_out/tmp/S2_m.fasta_1_p &
ssh bsidna23 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_2 /mnt/work/blast_filter_out/tmp/S2_m.fasta_2_p &
ssh bsidna24 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_3 /mnt/work/blast_filter_out/tmp/S2_m.fasta_3_p &
ssh bsidna25 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_4 /mnt/work/blast_filter_out/tmp/S2_m.fasta_4_p &
ssh bsidna26 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_5 /mnt/work/blast_filter_out/tmp/S2_m.fasta_5_p &
ssh bsidna27 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_6 /mnt/work/blast_filter_out/tmp/S2_m.fasta_6_p &
ssh bsidna28 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_7 /mnt/work/blast_filter_out/tmp/S2_m.fasta_7_p &
ssh bsidna29 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_8 /mnt/work/blast_filter_out/tmp/S2_m.fasta_8_p &
ssh bsidna30 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_9 /mnt/work/blast_filter_out/tmp/S2_m.fasta_9_p &
wait
ssh bsidna4 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_10 /mnt/work/blast_filter_out/tmp/S2_m.fasta_10_p &
ssh bsidna5 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_11 /mnt/work/blast_filter_out/tmp/S2_m.fasta_11_p &
ssh bsidna6 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_12 /mnt/work/blast_filter_out/tmp/S2_m.fasta_12_p &
ssh bsidna7 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_13 /mnt/work/blast_filter_out/tmp/S2_m.fasta_13_p &
ssh bsidna8 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_14 /mnt/work/blast_filter_out/tmp/S2_m.fasta_14_p &
ssh bsidna9 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_15 /mnt/work/blast_filter_out/tmp/S2_m.fasta_15_p &
ssh bsidna10 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_16 /mnt/work/blast_filter_out/tmp/S2_m.fasta_16_p &
ssh bsidna11 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_17 /mnt/work/blast_filter_out/tmp/S2_m.fasta_17_p &
ssh bsidna14 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_18 /mnt/work/blast_filter_out/tmp/S2_m.fasta_18_p &
ssh bsidna15 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_19 /mnt/work/blast_filter_out/tmp/S2_m.fasta_19_p &
ssh bsidna19 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_20 /mnt/work/blast_filter_out/tmp/S2_m.fasta_20_p &
ssh bsidna20 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_21 /mnt/work/blast_filter_out/tmp/S2_m.fasta_21_p &
ssh bsidna23 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_22 /mnt/work/blast_filter_out/tmp/S2_m.fasta_22_p &
ssh bsidna24 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_23 /mnt/work/blast_filter_out/tmp/S2_m.fasta_23_p &
ssh bsidna25 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_24 /mnt/work/blast_filter_out/tmp/S2_m.fasta_24_p &
ssh bsidna26 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_25 /mnt/work/blast_filter_out/tmp/S2_m.fasta_25_p &
ssh bsidna27 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_26 /mnt/work/blast_filter_out/tmp/S2_m.fasta_26_p &
ssh bsidna28 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_27 /mnt/work/blast_filter_out/tmp/S2_m.fasta_27_p &
ssh bsidna29 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_28 /mnt/work/blast_filter_out/tmp/S2_m.fasta_28_p &
ssh bsidna30 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_29 /mnt/work/blast_filter_out/tmp/S2_m.fasta_29_p &
wait
ssh bsidna4 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_30 /mnt/work/blast_filter_out/tmp/S2_m.fasta_30_p &
ssh bsidna5 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_31 /mnt/work/blast_filter_out/tmp/S2_m.fasta_31_p &
ssh bsidna6 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_32 /mnt/work/blast_filter_out/tmp/S2_m.fasta_32_p &
ssh bsidna7 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_33 /mnt/work/blast_filter_out/tmp/S2_m.fasta_33_p &
ssh bsidna8 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_34 /mnt/work/blast_filter_out/tmp/S2_m.fasta_34_p &
ssh bsidna9 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_35 /mnt/work/blast_filter_out/tmp/S2_m.fasta_35_p &
ssh bsidna10 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_36 /mnt/work/blast_filter_out/tmp/S2_m.fasta_36_p &
ssh bsidna11 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_37 /mnt/work/blast_filter_out/tmp/S2_m.fasta_37_p &
ssh bsidna14 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_38 /mnt/work/blast_filter_out/tmp/S2_m.fasta_38_p &
ssh bsidna15 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_39 /mnt/work/blast_filter_out/tmp/S2_m.fasta_39_p &
ssh bsidna19 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_40 /mnt/work/blast_filter_out/tmp/S2_m.fasta_40_p &
ssh bsidna20 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_41 /mnt/work/blast_filter_out/tmp/S2_m.fasta_41_p &
ssh bsidna23 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_42 /mnt/work/blast_filter_out/tmp/S2_m.fasta_42_p &
ssh bsidna24 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_43 /mnt/work/blast_filter_out/tmp/S2_m.fasta_43_p &
ssh bsidna25 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_44 /mnt/work/blast_filter_out/tmp/S2_m.fasta_44_p &
ssh bsidna26 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_45 /mnt/work/blast_filter_out/tmp/S2_m.fasta_45_p &
ssh bsidna27 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_46 /mnt/work/blast_filter_out/tmp/S2_m.fasta_46_p &
ssh bsidna28 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_47 /mnt/work/blast_filter_out/tmp/S2_m.fasta_47_p &
ssh bsidna29 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_48 /mnt/work/blast_filter_out/tmp/S2_m.fasta_48_p &
ssh bsidna30 /mnt/cluster/xdeng/script/dna2prot.py /mnt/work/blast_filter_out/tmp/S2_m.fasta_49 /mnt/work/blast_filter_out/tmp/S2_m.fasta_49_p &
wait
