ssh bsidna4 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk0 name=S1_chunk0 k=31 se=/mnt/work/fastq/S1abyss.fq_0" &
ssh bsidna5 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk1 name=S1_chunk1 k=31 se=/mnt/work/fastq/S1abyss.fq_1" &
ssh bsidna6 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk2 name=S1_chunk2 k=31 se=/mnt/work/fastq/S1abyss.fq_2" &
ssh bsidna7 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk3 name=S1_chunk3 k=31 se=/mnt/work/fastq/S1abyss.fq_3" &
ssh bsidna8 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk4 name=S1_chunk4 k=31 se=/mnt/work/fastq/S1abyss.fq_4" &
ssh bsidna9 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk5 name=S1_chunk5 k=31 se=/mnt/work/fastq/S1abyss.fq_5" &
ssh bsidna10 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk6 name=S1_chunk6 k=31 se=/mnt/work/fastq/S1abyss.fq_6" &
ssh bsidna11 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk7 name=S1_chunk7 k=31 se=/mnt/work/fastq/S1abyss.fq_7" &
ssh bsidna14 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk8 name=S1_chunk8 k=31 se=/mnt/work/fastq/S1abyss.fq_8" &
ssh bsidna15 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk9 name=S1_chunk9 k=31 se=/mnt/work/fastq/S1abyss.fq_9" &
ssh bsidna19 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk10 name=S1_chunk10 k=31 se=/mnt/work/fastq/S1abyss.fq_10" &
ssh bsidna20 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk11 name=S1_chunk11 k=31 se=/mnt/work/fastq/S1abyss.fq_11" &
ssh bsidna23 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk12 name=S1_chunk12 k=31 se=/mnt/work/fastq/S1abyss.fq_12" &
ssh bsidna24 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk13 name=S1_chunk13 k=31 se=/mnt/work/fastq/S1abyss.fq_13" &
ssh bsidna25 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk14 name=S1_chunk14 k=31 se=/mnt/work/fastq/S1abyss.fq_14" &
ssh bsidna26 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk15 name=S1_chunk15 k=31 se=/mnt/work/fastq/S1abyss.fq_15" &
ssh bsidna27 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk16 name=S1_chunk16 k=31 se=/mnt/work/fastq/S1abyss.fq_16" &
ssh bsidna28 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk17 name=S1_chunk17 k=31 se=/mnt/work/fastq/S1abyss.fq_17" &
ssh bsidna29 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk18 name=S1_chunk18 k=31 se=/mnt/work/fastq/S1abyss.fq_18" &
ssh bsidna30 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S1_chunk19 name=S1_chunk19 k=31 se=/mnt/work/fastq/S1abyss.fq_19" &
wait
ssh bsidna4 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk0 name=S2_chunk0 k=31 se=/mnt/work/fastq/S2abyss.fq_0" &
ssh bsidna5 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk1 name=S2_chunk1 k=31 se=/mnt/work/fastq/S2abyss.fq_1" &
ssh bsidna6 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk2 name=S2_chunk2 k=31 se=/mnt/work/fastq/S2abyss.fq_2" &
ssh bsidna7 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk3 name=S2_chunk3 k=31 se=/mnt/work/fastq/S2abyss.fq_3" &
ssh bsidna8 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk4 name=S2_chunk4 k=31 se=/mnt/work/fastq/S2abyss.fq_4" &
ssh bsidna9 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk5 name=S2_chunk5 k=31 se=/mnt/work/fastq/S2abyss.fq_5" &
ssh bsidna10 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk6 name=S2_chunk6 k=31 se=/mnt/work/fastq/S2abyss.fq_6" &
ssh bsidna11 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk7 name=S2_chunk7 k=31 se=/mnt/work/fastq/S2abyss.fq_7" &
ssh bsidna14 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk8 name=S2_chunk8 k=31 se=/mnt/work/fastq/S2abyss.fq_8" &
ssh bsidna15 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk9 name=S2_chunk9 k=31 se=/mnt/work/fastq/S2abyss.fq_9" &
ssh bsidna19 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk10 name=S2_chunk10 k=31 se=/mnt/work/fastq/S2abyss.fq_10" &
ssh bsidna20 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk11 name=S2_chunk11 k=31 se=/mnt/work/fastq/S2abyss.fq_11" &
ssh bsidna23 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk12 name=S2_chunk12 k=31 se=/mnt/work/fastq/S2abyss.fq_12" &
ssh bsidna24 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk13 name=S2_chunk13 k=31 se=/mnt/work/fastq/S2abyss.fq_13" &
ssh bsidna25 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk14 name=S2_chunk14 k=31 se=/mnt/work/fastq/S2abyss.fq_14" &
ssh bsidna26 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk15 name=S2_chunk15 k=31 se=/mnt/work/fastq/S2abyss.fq_15" &
ssh bsidna27 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk16 name=S2_chunk16 k=31 se=/mnt/work/fastq/S2abyss.fq_16" &
ssh bsidna28 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk17 name=S2_chunk17 k=31 se=/mnt/work/fastq/S2abyss.fq_17" &
ssh bsidna29 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk18 name=S2_chunk18 k=31 se=/mnt/work/fastq/S2abyss.fq_18" &
ssh bsidna30 "cd /mnt/work && /mnt/cluster/tools/abyss/bin/abyss-pe -C /mnt/work/abyss_S2_chunk19 name=S2_chunk19 k=31 se=/mnt/work/fastq/S2abyss.fq_19" &
wait
